-- AlterTable
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "ai_minutes_limit" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "forwarded_minutes_limit" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "agent_limit" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "plans" ADD COLUMN IF NOT EXISTS "onboarding_fee" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "plans" ALTER COLUMN "messageLimit" SET DEFAULT 0;
